spring:
  datasource:
    url: jdbc:mysql://localhost:13306/order?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  sql:
    init:
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
      mode: always
